### ISSUE TITLE
make bitstream error

### ISSUE THREAD

**Issue by zhangliang1997** [HSA-on-FPGA/HSA-on-FPGA#4]
Hi, HSA teams:
when i run make bitstream, i got an error:

create_bd_cell -type ip -vlnv fau.de:hsa:packet_processor:2.0 packet_processor_0
ERROR: [BD 5-390] IP definition not found for VLNV: fau.de:hsa:packet_processor:2.0 
ERROR: [Common 17-39] 'create_bd_cell' failed due to earlier errors.

can give me some adivce?

**Comment by phholzinger** [comment]
Seems like an issue with an incorrectly set path. At which stage of the process do you encounter this error? Does "make build_backend" successfully build? Can you give me complete log of what happend when you ran the "make bitstream" command?
